# Generated by Django 5.0 on 2023-12-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('middleName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=122)),
                ('contactNumber', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=20)),
                ('academicPercentage', models.CharField(max_length=5)),
                ('activeBacklogs', models.CharField(max_length=10)),
                ('streetAddress', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
            ],
        ),
    ]
